### ISSUE TITLE
训练错误，self._traceback = tf_stack.extract_stack()，加载预训练模型错误

### ISSUE THREAD

**Issue by leandepk** [DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation#75]
我每一步都是按照readme来的，在最后的训练的时候报以下错误
Traceback (most recent call last):
  File "/home/china/anaconda3/envs/yiweichao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/china/anaconda3/envs/yiweichao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/china/anaconda3/envs/yiweichao/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[{{node get_batch/batch}}]]
	 [[strided_slice_19/_373]]
  (1) Out of range: PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 2, current size 0)
	 [[{{node get_batch/batch}}]]
0 successful operations.
0 derived errors ignored.
我感觉像是加载预训练模型时候出的问题，我从网上下载了pretrained model，也放到了相应的文件夹，但是下载的模型的名字好像不一样，我就改了下，但还是训练不起来，有没有知道为什么呀？

**Comment by leandepk** [comment]
好了，我发现是自己做tfrecord出了问题，现在已经可以训练了
